start-at-login =  true

after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

[mode.main.binding]
    cmd-enter = "exec-and-forget open -n -a /Applications/Alacritty.app"
    cmd-p = 'exec-and-forget open -a "Brave Browser.app" -n --args --incognito'
    # Layout
    cmd-slash = 'layout tiles horizontal vertical'
    cmd-comma = 'layout accordion horizontal vertical'

    # Focus
    alt-f = 'fullscreen'
    cmd-h = 'focus left'
    cmd-j = 'focus down'
    cmd-k = 'focus up'
    cmd-l = 'focus right'

    # Move windows
    cmd-shift-h = 'move left'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-l = 'move right'

    # Resize
    cmd-minus = 'resize smart -50'
    cmd-equal = 'resize smart +50'

    # Workspaces
    cmd-1 = 'workspace 1-uni'
    cmd-2 = 'workspace 2-work'
    cmd-3 = 'workspace 3-resume'
    cmd-4 = 'workspace 4-prep'
    cmd-5 = 'workspace 5-utils'
    cmd-6 = 'workspace 6-bridge'
    cmd-7 = 'workspace 7-oss'
    cmd-8 = 'workspace 8-proj'
    cmd-9 = 'workspace 9-proj-2'
    cmd-0 = 'workspace 10-comms'

    # Move window to workspace
    cmd-shift-1 = 'move-node-to-workspace 1-uni'
    cmd-shift-2 = 'move-node-to-workspace 2-work'
    cmd-shift-3 = 'move-node-to-workspace 3-resume'
    cmd-shift-4 = 'move-node-to-workspace 4-prep'
    cmd-shift-5 = 'move-node-to-workspace 5-utils'
    cmd-shift-6 = 'move-node-to-workspace 6-bridge'
    cmd-shift-7 = 'move-node-to-workspace 7-oss'
    cmd-shift-8 = 'move-node-to-workspace 8-proj'
    cmd-shift-9 = 'move-node-to-workspace 9-proj-2'
    cmd-shift-0 = 'move-node-to-workspace 10-comms'

    # Workspace navigation
    cmd-tab = 'workspace-back-and-forth'

    # Move workspace to next monitor
    cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # Service mode
    cmd-shift-semicolon = 'mode service'


[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    cmd-shift-h = ['join-with left', 'mode main']
    cmd-shift-j = ['join-with down', 'mode main']
    cmd-shift-k = ['join-with up', 'mode main']
    cmd-shift-l = ['join-with right', 'mode main']


[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.right = 10
outer.top = 10
outer.bottom = 10
