[window]
opacity = 0.70
blur = true
decorations = "Full"
decorations_theme_variant = "Dark"

  [window.dimensions]
  columns = 80
  lines = 80

  [window.padding]
  x = 16
  y = 16

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[font]
size = 18

  [font.normal]
  family = "FantasqueSansM Nerd Font"
  style = "Regular"

[colors.primary]
background = "#000000" # Example: A dark gray background color
foreground = "#FFFFFF" # Example: A light gray foreground color
# [general]
# import = [
#   "/home/sleepy/.config/alacritty/themes/themes/dracula.toml"
# ]
